### ISSUE TITLE
Switching to a different browser tab, and switching back, causes error

### ISSUE THREAD

**Issue by sboagy** [sboagy/tunetrees#112]
An error occurs when switching to a different browser tab, and switching back.

The error on the client side is:

```
ClientFetchError: Read more at https://errors.authjs.dev#autherror
    at fetchData (webpack-internal:///(app-pages-browser)/./node_modules/next-auth/lib/client.js:49:22)
    at async getSession (webpack-internal:///(app-pages-browser)/./node_modules/next-auth/react.js:117:21)
    at async SessionProvider.useEffect [as _getSession] (webpack-internal:///(app-pages-browser)/./node_modules/next-auth/react.js:288:51) {name: 'ClientFetchError', type: 'AuthError', kind: 'error', message: 'Read more at https://errors.authjs.dev#autherror', stack: 'ClientFetchError
    at fetchData (webpack-in…er)/./node_modules/next-auth/react.js:288:51)'}
```

The error on the server side is:

```
[auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at [https://errors.authjs.dev#unknownaction](vscode-file://vscode-app/Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) at parseActionAndProviderId (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/web.js:106:15) at toInternalRequest (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/web.js:37:40) at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:87:103) at httpHandler (webpack-internal:///(rsc)/./node_modules/next-auth/index.js:142:82) at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:80:14) at AppRouteRouteModule.do (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33392) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:42828 at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:171:36 at NoopContextManager.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062) at ContextAPI.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) at NoopTracer.startActiveSpan (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093) at ProxyTracer.startActiveSpan (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:153:103 at NoopContextManager.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062) at ContextAPI.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) at NextTracerImpl.trace (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:153:28) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:42689 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40501 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40458 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at AppRouteRouteModule.handle (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40412) at doRender (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1455:60) at responseGenerator (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1814:34) at ResponseCache.get (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/response-cache/index.js:49:20) at DevServer.renderToResponseWithComponentsImpl (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1824:53) [auth][debug]: request {} [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at [https://errors.authjs.dev#unknownaction](vscode-file://vscode-app/Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) at parseActionAndProviderId (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/web.js:106:15) at toInternalRequest (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/lib/utils/web.js:37:40) at Auth (webpack-internal:///(rsc)/./node_modules/next-auth/node_modules/@auth/core/index.js:87:103) at httpHandler (webpack-internal:///(rsc)/./node_modules/next-auth/index.js:142:82) at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:80:14) at AppRouteRouteModule.do (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33392) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:42828 at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:171:36 at NoopContextManager.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062) at ContextAPI.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) at NoopTracer.startActiveSpan (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093) at ProxyTracer.startActiveSpan (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:153:103 at NoopContextManager.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062) at ContextAPI.with (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) at NextTracerImpl.trace (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/lib/trace/tracer.js:153:28) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:42689 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40501 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at /Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40458 at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14) at AppRouteRouteModule.handle (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40412) at doRender (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1455:60) at responseGenerator (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1814:34) at ResponseCache.get (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/response-cache/index.js:49:20) at DevServer.renderToResponseWithComponentsImpl (/Users/sboag/gittt/tunetrees/frontend/node_modules/next/dist/server/base-server.js:1824:53) [auth][debug]: request {}
```

**Comment by sboagy** [comment]
Fix for this was commenting out:

```
basePath: BASE_PATH,
```

in auth/index.ts.
